### ISSUE TITLE
Fix GitHub Actions deployment workflow authentication

### ISSUE THREAD

**Issue by bhouston** [drivecore/mycoder-docs#20]
## GitHub Actions Deployment Workflow Failing

The deployment workflow (`deploy-docs.yml`) is failing because it's configured to use Workload Identity Federation (WIF) but the required secrets aren't available.

### Current Configuration
The workflow is trying to use:
- `${{ secrets.WIF_PROVIDER }}`
- `${{ secrets.WIF_SERVICE_ACCOUNT }}`

### Available Secrets
- `GCP_SA_KEY` - Appears to be a service account key

### Proposed Solution
Update the workflow to use the service account key authentication method instead of Workload Identity Federation, or add the missing WIF secrets.

#### Option 1: Use Service Account Key
Replace the Google Auth step with:
```yaml
- name: Google Auth
  id: auth
  uses: google-github-actions/auth@v2
  with:
    credentials_json: ${{ secrets.GCP_SA_KEY }}
```

#### Option 2: Add Missing WIF Secrets
Add the required WIF secrets to the repository:
- `WIF_PROVIDER`: The Workload Identity Provider ID
- `WIF_SERVICE_ACCOUNT`: The service account email to impersonate

Option 1 is quicker to implement but using Workload Identity Federation (Option 2) is Google's recommended approach for security.
