### ISSUE TITLE
Add missing tags to tags.yml to resolve build warnings

### ISSUE THREAD

**Issue by bhouston** [drivecore/mycoder-docs#23]
### Description
When building the project, the following warnings appear:

```
[WARNING] Tags [ai, coding] used in agentic-coding-guidelines.md are not defined in tags.yml
[WARNING] Tags [ai, programming, development, tools] used in mycoder-v0-5-0-release.md are not defined in tags.yml
[WARNING] Tags [ai, programming, development, tools, case-study] used in how-we-use-mycoder-to-build-mycoder.md are not defined in tags.yml
```

These warnings occur because several tags used in blog posts are not defined in the `blog/tags.yml` file.

### Required Changes
The following tags need to be added to `blog/tags.yml`:
- `ai`
- `coding`
- `programming`
- `development`
- `tools`
- `case-study`

### Current tags.yml Content
```yml
facebook:
  label: Facebook
  permalink: /facebook
  description: Facebook tag description

hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus tag description

hola:
  label: Hola
  permalink: /hola
  description: Hola tag description
```

### Expected Outcome
After adding the missing tags, the build warnings should be resolved, and the tags should be properly linked in the blog posts.

### Priority
Medium - These are warnings, not errors, but should be addressed to ensure proper blog post categorization and navigation.
