### ISSUE TITLE
Enhance Author Profiles with Additional Social Links

### ISSUE THREAD

**Issue by bhouston** [drivecore/mycoder-docs#5]
## Enhance Author Profiles with Additional Social Links

Currently, our author profiles include limited social links (GitHub and Twitter). We should expand these to include additional platforms and ensure all naming is up-to-date.

### Tasks:
- [ ] Update Twitter references to X (formerly Twitter)
- [ ] Add support for Bluesky social links in author profiles
- [ ] Add support for Mastodon social links in author profiles
- [ ] Ensure proper icons are used for each platform
- [ ] Update the `authors.yml` file with these additional social links
- [ ] Document the expanded social link options for future authors

### Implementation Details:
- The author profiles are defined in `/blog/authors.yml`
- Docusaurus may need configuration updates to support additional social platforms
- Icons for new platforms may need to be added

### Example Updated Author Entry:
```yaml
ben:
  name: Ben Houston
  title: Founder of DriveCore
  url: https://github.com/bhouston
  image_url: https://github.com/bhouston.png
  socials:
    github: bhouston
    x: BenHouston3D  # Updated from twitter
    bluesky: benhouston.bsky.social
    mastodon: @benhouston@fosstodon.org
```

### Benefits:
- More comprehensive author profiles
- Support for modern social platforms
- Up-to-date terminology (X instead of Twitter)

### References:
- [Docusaurus Blog Authors Documentation](https://docusaurus.io/docs/blog#blog-authors)
- Current author profiles in `/blog/authors.yml`
